name: winterflowspace

namespace: flowception
env:
  APP_VERSION: a13e18ae1a1561d3ef5a0b54200c21d56a369261

deployment:
  - name: winterflowspace
    image: invisibug/winterflowspace
    ports:
      - port: 80
    # env:
    # Handled in Dockerfile.live

ingress:
  - name: winterflowspace.com
    selector: winterflowspace
    path: /.*
    port: 80
    host: winterflowspace.com

service:
  loadBalancer:
    - name: winterflowspace
      selector: winterflowspace
      port: 80
