name: winterflowspace

namespace: flowception
env:
  APP_VERSION: cf1daa03c9233708c82f3343089ef4befb6b49d9

deployment:
  - name: winterflowspace
    image: invisibug/winterflowspace
    ports:
      - port: 80
    # env:
    # Handled in Dockerfile.live

ingress:
  - name: winterflowspace.com
    selector: winterflowspace
    path: /.*
    port: 80
    host: winterflowspace.com

service:
  loadBalancer:
    - name: winterflowspace
      selector: winterflowspace
      port: 80
