name: winterflowspace

namespace: flowception
env:
  APP_VERSION: a3e4481e21b602f7e689ad5b9e8bee8d472bf21d

deployment:
  - name: winterflowspace
    image: invisibug/winterflowspace
    ports:
      - port: 80
    # env:
    # Handled in Dockerfile.live

ingress:
  - name: winterflowspace.com
    selector: winterflowspace
    path: /.*
    port: 80
    host: winterflowspace.com

service:
  loadBalancer:
    - name: winterflowspace
      selector: winterflowspace
      port: 80
