name: winterflowspace

namespace: flowception
env:
  APP_VERSION: 4ae8866720a677f0dca5f78b6072622b9aa31f45

deployment:
  - name: winterflowspace
    image: invisibug/winterflowspace
    ports:
      - port: 80
    # env:
    # Handled in Dockerfile.live

ingress:
  - name: winterflowspace.com
    selector: winterflowspace
    path: /.*
    port: 80
    host: winterflowspace.com

service:
  loadBalancer:
    - name: winterflowspace
      selector: winterflowspace
      port: 80
