name: winterflowspace-test

namespace: flowception
env:
  APP_VERSION: 4be2dec3cddcae63fe53876d922e57d04c3bf8bb

deployment:
  - name: winterflowspace-test
    image: invisibug/winterflowspace-test
    ports:
      - port: 80
    # env:
    # Handled in Dockerfile.argo.test

ingress:
  - name: test.winterflowspace.com
    selector: winterflowspace-test
    path: /
    port: 80
    host: test.winterflowspace.com

service:
  loadBalancer:
    - name: winterflowspace-test
      selector: winterflowspace-test
      port: 80
