name: winterflowspace-test

namespace: flowception
env:
  APP_VERSION: e311b4e0f9dd7971ae3b35c8ae4dbae5794328cb

deployment:
  - name: winterflowspace-test
    image: invisibug/winterflowspace-test
    ports:
      - port: 80
    # env:
    # Handled in Dockerfile.argo.test

ingress:
  - name: test.winterflowspace.com
    selector: winterflowspace-test
    path: /
    port: 80
    host: test.winterflowspace.com

service:
  loadBalancer:
    - name: winterflowspace-test
      selector: winterflowspace-test
      port: 80
