apiVersion: v2
name: winterflowspace
description: A Helm chart for Kubernetes
type: application

version: 0.1.0
dependencies:
  - name: library
    version: ~1
    repository: "https://invisibug.github.io/kavanetes-helm/"

appVersion: "1.0.0"
