name: test pipeline

on:
  push:
    branches:
      - test-release

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_KEY: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_NAME: winterflowspace-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_KEY }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile.argo
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  update-app-version:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update values.yaml
        run: |
          cd kube
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' ./values/test.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ./values/test.yaml
          git commit -m "update app version.yaml"
          git push

  deploy-to-test:
    needs: update-app-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge test-release -> test
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: New app version created '${{ github.sha }}'
          from_branch: test-release
          target_branch: test
          github_token: ${{ secrets.ACCESS_TOKEN }}

  # sync-dev:
  #   needs: deploy-to-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master

  #     - name: Merge test-release -> test
  #       uses: devmasx/merge-branch@master
  #       with:
  #         type: now
  #         from_branch: test
  #         message: fast-forward dev
  #         target_branch: dev
  #         github_token: ${{ secrets.ACCESS_TOKEN }}
